"""Agregar columnas ancho_pesos y ancho_dolares a PatronDB

Revision ID: e3d1f610d817
Revises: 
Create Date: 2025-04-22 19:51:48.755130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d1f610d817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_gmail_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('contenido_mail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mails_id'), 'mails', ['id'], unique=False)
    op.create_table('patrones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transacion', sa.String(), nullable=True),
    sa.Column('transaccion_cuota', sa.String(), nullable=True),
    sa.Column('fecha_cierre', sa.String(), nullable=True),
    sa.Column('fecha_vencimiento', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('ancho_maximo', sa.Integer(), nullable=True),
    sa.Column('ancho_pesos', sa.Integer(), nullable=True),
    sa.Column('ancho_dolares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrones_id'), 'patrones', ['id'], unique=False)
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('patron_busqueda', sa.String(), nullable=True),
    sa.Column('patron_link_descarga', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('archivo_adjunto', sa.Boolean(), nullable=True),
    sa.Column('patrones_visa', sa.Integer(), nullable=True),
    sa.Column('patrones_amex', sa.Integer(), nullable=True),
    sa.Column('patrones_mastercard', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patrones_amex'], ['patrones.id'], ),
    sa.ForeignKeyConstraint(['patrones_mastercard'], ['patrones.id'], ),
    sa.ForeignKeyConstraint(['patrones_visa'], ['patrones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_bancos_id'), 'bancos', ['id'], unique=False)
    op.create_table('resumenes_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('mail_id', sa.Integer(), nullable=True),
    sa.Column('link_descarga', sa.String(), nullable=True),
    sa.Column('contenido_pdf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mail_id'], ['mails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_pdf_id'), 'resumenes_pdf', ['id'], unique=False)
    op.create_table('resumenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emision', sa.Date(), nullable=True),
    sa.Column('vencimiento', sa.Date(), nullable=True),
    sa.Column('cierre', sa.Date(), nullable=True),
    sa.Column('banco_id', sa.Integer(), nullable=True),
    sa.Column('mail_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['mail_id'], ['mails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_id'), 'resumenes', ['id'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('comercio', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=True),
    sa.Column('resumen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resumen_id'], ['resumenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.create_table('cuotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_cuotas', sa.Integer(), nullable=True),
    sa.Column('numero_cuota_pagada', sa.Integer(), nullable=True),
    sa.Column('gasto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuotas_id'), 'cuotas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuotas_id'), table_name='cuotas')
    op.drop_table('cuotas')
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_resumenes_id'), table_name='resumenes')
    op.drop_table('resumenes')
    op.drop_index(op.f('ix_resumenes_pdf_id'), table_name='resumenes_pdf')
    op.drop_table('resumenes_pdf')
    op.drop_index(op.f('ix_bancos_id'), table_name='bancos')
    op.drop_table('bancos')
    op.drop_index(op.f('ix_patrones_id'), table_name='patrones')
    op.drop_table('patrones')
    op.drop_index(op.f('ix_mails_id'), table_name='mails')
    op.drop_table('mails')
    # ### end Alembic commands ###
